export const data = [
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم  1",
    Importance_Level: "مهمة جدا",
    Assigned_To: "فهد",
    Due_Date: "September 07, 2024",
    Case_Name: "القضية رقم 6",
    Task_Status: "قيدالانتظار",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم  2",
    Importance_Level: "متوسطة الاهمية",
    Assigned_To: "محمد",
    Due_Date: "September 10, 2024 ",
    Case_Name: "القضية رقم 5",
    Task_Status: "مكتملة",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم  3",
    Importance_Level: "ذات اهمية ضعيفة",
    Assigned_To: "احمد",
    Due_Date: "September 11, 2024 ",
    Case_Name: "القضية رقم 4",
    Task_Status: "قيد التنفيذ",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم  4",
    Importance_Level: "مهمة جدا",
    Assigned_To: "على",
    Due_Date: "September 24, 2024 ",
    Case_Name: "القضية رقم 3",
    Task_Status: "قيدالانتظار",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم  5",
    Importance_Level: "متوسطة الاهمية",
    Assigned_To: "محمد",
    Due_Date: "September 01, 2024 ",
    Case_Name: "القضية رقم 2",
    Task_Status: "مكتملة",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم  6",
    Importance_Level: "ذات اهمية ضعيفة",
    Assigned_To: "مصطفى",
    Due_Date: "September 27, 2024 ",
    Case_Name: "القضية رقم 1",
    Task_Status: "قيد التنفيذ",
  },
];
