export const data = [
  {
    id: "TASK-8782",
    Name: "على",
    Address: "الرياض",
    Mobile_Number: "+20112734455",
    Email: "ali@gmail.com",
    Current_Case_Name: "القضية رقم 6",
  },
  {
    id: "TASK-8782",
    Name: "محمد",
    Address: "الدمام",
    Mobile_Number: "+201173534455",
    Email: "mohamedb@gmail.com",
    Current_Case_Name: "القضية رقم 5",
  },
  {
    id: "TASK-8782",
    Name: "احمد",
    Address: "الرياض",
    Mobile_Number: "+201174334455",
    Email: "ahmed@gmail.com",
    Current_Case_Name: "القضية رقم 4",
  },
  {
    id: "TASK-8782",
    Name: "فهد",
    Address: "الدمام",
    Mobile_Number: "+201672334455",
    Email: "fahd@gmail.com",
    Current_Case_Name: "القضية رقم 3",
  },
  {
    id: "TASK-8782",
    Name: "حمد",
    Address: "جده",
    Mobile_Number: "+201542334455",
    Email: "hamd@gmail.com",
    Current_Case_Name: "القضية رقم 2",
  },
  {
    id: "TASK-8782",
    Name: "عبدالله",
    Address: "الطائف",
    Mobile_Number: "+201122334455",
    Email: "abdullah@gmail.com",
    Current_Case_Name: "القضية رقم 1",
  },
];
