export const data = [
  {
    id: "TASK-8782",
    Name: "Ali",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+20112734455",
    Email: "c@gmail.com",
    Current_Case_Name: "Mustafa",
  },
  {
    id: "TASK-8782",
    Name: "Mustafa",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201173534455",
    Email: "b@gmail.com",
    Current_Case_Name: "Mustafa",
  },
  {
    id: "TASK-8782",
    Name: "Abdullah",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201174334455",
    Email: "ab@gmail.com",
    Current_Case_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Name: "Ali",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201672334455",
    Email: "xyz@gmail.com",
    Current_Case_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Name: "mohamed",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201542334455",
    Email: "abc@gmail.com",
    Current_Case_Name: "Mustafa",
  },
  {
    id: "TASK-8782",
    Name: "mohamed",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201122334455",
    Email: "a@gmail.com",
    Current_Case_Name: "Abdullah",
  },
];
