export const data = [
  {
    id: "TASK-8782",
    Name: "mohamed",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201122334455",
    Email: "mohamedabdelghany937@gmail.com",
    Current_Case_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Name: "mohamed",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201122334455",
    Email: "mohamedabdelghany937@gmail.com",
    Current_Case_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Name: "mohamed",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201122334455",
    Email: "mohamedabdelghany937@gmail.com",
    Current_Case_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Name: "mohamed",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201122334455",
    Email: "mohamedabdelghany937@gmail.com",
    Current_Case_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Name: "mohamed",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201122334455",
    Email: "mohamedabdelghany937@gmail.com",
    Current_Case_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Name: "mohamed",
    Address: "Saudi Arabia ,Riyadh",
    Mobile_Number: "+201122334455",
    Email: "mohamedabdelghany937@gmail.com",
    Current_Case_Name: "Ali",
  },
];
