export const data = [
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "قيد التنفيذ",
    Importance_Level: "ذات اهمية ضعيفة",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "قيدالانتظار",
    Importance_Level: "متوسطة الاهمية",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "مكتملة",
    Importance_Level: "متوسطة الاهمية",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "قيدالانتظار",
    Importance_Level: "مهمة جدا",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "مكتملة",
    Importance_Level: "ذات اهمية ضعيفة",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "قيدالانتظار",
    Importance_Level: "مهمة جدا",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "قيد التنفيذ",
    Importance_Level: "متوسطة الاهمية",
  },
];
