export const data = [
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "Progress",
    Importance_Level: "low",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "Pending",
    Importance_Level: "meduim",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "Completed",
    Importance_Level: "meduim",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "Pending",
    Importance_Level: "high",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "Completed",
    Importance_Level: "low",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "Pending",
    Importance_Level: "high",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Case_Name: "Ali",
    Due_Date: "September 12, 2024 12:11 PM",
    Task_Status: "Progress",
    Importance_Level: "meduim",
  },
];
