export const data = [
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 1",
    Case_Number: "12311",
    Court_Name: " 1المحكمة رقم ",
    Court_Category: "جنائي",
    Case_Status: "مكتملة",
    Client_Name: "خالد",
    Hearing_Dates: "September 21, 2024",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 2",
    Case_Number: "12311",
    Court_Name: "المحكمة رقم  2",
    Court_Category: "مدنى",
    Case_Status: "قيدالانتظار",
    Client_Name: "فهد",
    Hearing_Dates: "September 12, 2024",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 3",
    Case_Number: "12311",
    Court_Name: "المحكمة رقم  3",
    Court_Category: "عائلى",
    Case_Status: "قيد التنفيذ",
    Client_Name: "مصطفى",
    Hearing_Dates: "September 16, 2024",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 4",
    Case_Number: "12311",
    Court_Name: "المحكمة رقم  4",
    Court_Category: "جنائي",
    Case_Status: "مكتملة",
    Client_Name: "عبدالله",
    Hearing_Dates: "September 19, 2024",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 5",
    Case_Number: "12311",
    Court_Name: "المحكمة رقم 5",
    Court_Category: "عائلى",
    Case_Status: "قيدالانتظار",
    Client_Name: "احمد",
    Hearing_Dates: "September 02, 2024",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 6",
    Case_Number: "12311",
    Court_Name: "Court 1",
    Court_Category: "مدنى",
    Case_Status: "قيد التنفيذ",
    Client_Name: "محمد",
    Hearing_Dates: "September 24, 2024",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 6",
    Case_Number: "12311",
    Court_Name: "المحكمة رقم  6",
    Court_Category: "جنائي",
    Case_Status: "مكتملة",
    Client_Name: "على",
    Hearing_Dates: "September 07, 2024",
  },
];
