export const data = [
  {
    id: "TASK-8782",
    Title: "طلب رقم 1",
    Client_Name: "القضية رقم1",
    Lawyer_Name: "المحامى رقم1",
    Image: "https://picsum.photos/200/300?random=13",
    Date: "September 03, 2024 ",
    Order_Status: "تم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 2",
    Lawyer_Name: "المحامى رقم2",
    Image: "https://picsum.photos/200/300?random=12",
    Client_Name: "القضية رقم2",
    Date: "September 08, 2024 ",
    Order_Status: "لم يتم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 3",
    Lawyer_Name: "3",
    Image: "https://picsum.photos/200/300?random=11",
    Client_Name: "القضية رقم3",
    Date: "September 10, 2024 ",
    Order_Status: "لم يتم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 4",
    Lawyer_Name: "المحامى رقم4",
    Image: "https://picsum.photos/200/300?random=16",
    Client_Name: "القضية رقم 4",
    Date: "September 12, 2024 ",
    Order_Status: "لم يتم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 5",
    Lawyer_Name: "المحامى رقم5",
    Image: "https://picsum.photos/200/300?random=23",
    Client_Name: "القضية رقم5",
    Date: "September 11, 2024 ",
    Order_Status: "تم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 6",
    Lawyer_Name: "المحامى رقم6",
    Image: "https://picsum.photos/200/300?random=21",
    Client_Name: "القضية رقم 6",
    Date: "September 17, 2024 ",
    Order_Status: "تم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 7",
    Lawyer_Name: "المحامى رقم7",
    Image: "https://picsum.photos/200/300?random=22",
    Client_Name: "القضية رقم 7",
    Date: "September 16, 2024 ",
    Order_Status: "تم الرد",
  },
];
