export const data = [
  {
    id: "TASK-8782",
    Title: "طلب رقم 1",
    Client_Name: "القضية رقم1",
    Date: "September 03, 2024 ",
    Order_Status: "تم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 2",
    Client_Name: "القضية رقم2",
    Date: "September 08, 2024 ",
    Order_Status: "لم يتم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 3",
    Client_Name: "القضية رقم3",
    Date: "September 10, 2024 ",
    Order_Status: "لم يتم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 4",
    Client_Name: "القضية رقم 4",
    Date: "September 12, 2024 ",
    Order_Status: "لم يتم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 5",
    Client_Name: "القضية رقم5",
    Date: "September 11, 2024 ",
    Order_Status: "تم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 6",
    Client_Name: "القضية رقم 6",
    Date: "September 17, 2024 ",
    Order_Status: "تم الرد",
  },
  {
    id: "TASK-8782",
    Title: "طلب رقم 6",
    Client_Name: "القضية رقم 7",
    Date: "September 16, 2024 ",
    Order_Status: "تم الرد",
  },
];
