export const data = [
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Importance_Level: "high",
    Assigned_To: "Ahmed",
    Due_Date: "September 12, 2024 12:11 PM",
    Case_Name: "Ali",
    Task_Status: "Pending",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK2",
    Importance_Level: "meduim",
    Assigned_To: "Mohamed",
    Due_Date: "September 12, 2024 12:11 PM",
    Case_Name: "Abdullah",
    Task_Status: "Completed",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK2",
    Importance_Level: "low",
    Assigned_To: "Abdullah",
    Due_Date: "September 12, 2024 12:11 PM",
    Case_Name: "Abdullah",
    Task_Status: "Progress",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Importance_Level: "high",
    Assigned_To: "Ahmed",
    Due_Date: "September 12, 2024 12:11 PM",
    Case_Name: "Ali",
    Task_Status: "Pending",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK2",
    Importance_Level: "meduim",
    Assigned_To: "Mohamed",
    Due_Date: "September 12, 2024 12:11 PM",
    Case_Name: "Abdullah",
    Task_Status: "Completed",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK2",
    Importance_Level: "low",
    Assigned_To: "Abdullah",
    Due_Date: "September 12, 2024 12:11 PM",
    Case_Name: "Abdullah",
    Task_Status: "Progress",
  },
];
