export const data = [
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Importance_Level: "مهمة جدا",
    Assigned_To: "Ahmed",
    Due_Date: "September 21, 2024 09:11 PM",
    Case_Name: "Ali",
    Task_Status: "قيدالانتظار",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK2",
    Importance_Level: "متوسطة الاهمية",
    Assigned_To: "Mohamed",
    Due_Date: "September 12, 2024 06:11 PM",
    Case_Name: "Abdullah",
    Task_Status: "مكتملة",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK2",
    Importance_Level: "ذات اهمية ضعيفة",
    Assigned_To: "Abdullah",
    Due_Date: "September 22, 2024 12:11 PM",
    Case_Name: "Abdullah",
    Task_Status: "قيد التنفيذ",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK1",
    Importance_Level: "مهمة جدا",
    Assigned_To: "Ahmed",
    Due_Date: "September 27, 2024 05:11 PM",
    Case_Name: "Ali",
    Task_Status: "قيدالانتظار",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK2",
    Importance_Level: "متوسطة الاهمية",
    Assigned_To: "Mohamed",
    Due_Date: "September 1, 2024 1:11 PM",
    Case_Name: "Abdullah",
    Task_Status: "مكتملة",
  },
  {
    id: "TASK-8782",
    Task_Name: "TASK2",
    Importance_Level: "ذات اهمية ضعيفة",
    Assigned_To: "Abdullah",
    Due_Date: "September 12, 2024 12:11 PM",
    Case_Name: "Abdullah",
    Task_Status: "قيد التنفيذ",
  },
];
