export const data = [
  {
    UserID: "TASK-8782",
    UserName: "property 1",
    Gender: "type 1",
    Phone: "system 1",
    Email: "Jeddah",
    JoinedDate: "September 12, 2024 12:11 PM",
  },
  {
    UserID: "TASK-8782",
    UserName: "property 1",
    Gender: "type 1",
    Phone: "system 1",
    Email: "Jeddah",
    JoinedDate: "September 12, 2024 12:11 PM",
  },
  {
    UserID: "TASK-8782",
    UserName: "property 1",
    Gender: "type 1",
    Phone: "system 1",
    Email: "Jeddah",
    JoinedDate: "September 12, 2024 12:11 PM",
  },
  {
    UserID: "TASK-8782",
    UserName: "property 1",
    Gender: "type 1",
    Phone: "system 1",
    Email: "Jeddah",
    JoinedDate: "September 12, 2024 12:11 PM",
  },
  {
    UserID: "TASK-8782",
    UserName: "property 1",
    Gender: "type 1",
    Phone: "system 1",
    Email: "Jeddah",
    JoinedDate: "September 12, 2024 12:11 PM",
  },
  {
    UserID: "TASK-8782",
    UserName: "property 1",
    Gender: "type 1",
    Phone: "system 1",
    Email: "Jeddah",
    JoinedDate: "September 12, 2024 12:11 PM",
  },
  {
    UserID: "TASK-8782",
    UserName: "property 1",
    Gender: "type 1",
    Phone: "system 1",
    Email: "Jeddah",
    JoinedDate: "September 12, 2024 12:11 PM",
  },
  {
    UserID: "TASK-8782",
    UserName: "property 1",
    Gender: "type 1",
    Phone: "system 1",
    Email: "Jeddah",
    JoinedDate: "September 12, 2024 12:11 PM",
  },
];
