export const data = [
  {
    id: "TASK-8782",
    Appointment_Title: "TASK1",
    Date : "September 12, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "Saudi Arabia ,Riyadh",
    Client_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "TASK1",
    Date : "September 12, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "Saudi Arabia ,Riyadh",
    Client_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "TASK1",
    Date : "September 12, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "Saudi Arabia ,Riyadh",
    Client_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "TASK1",
    Date : "September 12, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "Saudi Arabia ,Riyadh",
    Client_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "TASK1",
    Date : "September 12, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "Saudi Arabia ,Riyadh",
    Client_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "TASK1",
    Date : "September 12, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "Saudi Arabia ,Riyadh",
    Client_Name: "Ali",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "TASK1",
    Date : "September 12, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "Saudi Arabia ,Riyadh",
    Client_Name: "Ali",
  },
  
];
