export const data = [
  {
    id: "TASK-8782",
    Appointment_Title: "بخصوص القضية رقم 1",
    Date : "September 11, 2024",
    Time: "10:11 PM",
    Case_Name: "Ahmed",
    Location: "الرياض",
    Client_Name: "فهد",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "بخصوص القضية رقم  2",
    Date : "September 12, 2024",
    Time: "11:11 PM",
    Case_Name: "Ahmed",
    Location: "جده",
    Client_Name: "احمد",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "بخصوص القضية رقم  3",
    Date : "September 17, 2024",
    Time: "07:11 PM",
    Case_Name: "Ahmed",
    Location: "الدمام",
    Client_Name: "محمد",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "بخصوص القضية رقم 4",
    Date : "September 02, 2024",
    Time: "02:11 PM",
    Case_Name: "Ahmed",
    Location: "الرياض",
    Client_Name: "عبدالله",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "بخصوص القضية رقم  6",
    Date : "September 07, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "الدمام",
    Client_Name: "مصطفى",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "بخصوص القضية رقم 5",
    Date : "September 26, 2024",
    Time: "12:11 PM",
    Case_Name: "Ahmed",
    Location: "الرياض",
    Client_Name: "محمد",
  },
  {
    id: "TASK-8782",
    Appointment_Title: "بخصوص القضية رقم  7",
    Date : "September 22, 2024",
    Time: "04:11 PM",
    Case_Name: "Ahmed",
    Location: "جده",
    Client_Name: "على",
  },
  
];
