export const data = [
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Category: "Saudi Arabia ,Riyadh",
    Next_Appointment_Date: "September 12, 2024 ",
    Status: "mohamedabdelghany937@gmail.com",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Category: "Saudi Arabia ,Riyadh",
    Next_Appointment_Date: "September 12, 2024 ",
    Status: "mohamedabdelghany937@gmail.com",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Category: "Saudi Arabia ,Riyadh",
    Next_Appointment_Date: "September 12, 2024 ",
    Status: "mohamedabdelghany937@gmail.com",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Category: "Saudi Arabia ,Riyadh",
    Next_Appointment_Date: "September 12, 2024 ",
    Status: "mohamedabdelghany937@gmail.com",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Category: "Saudi Arabia ,Riyadh",
    Next_Appointment_Date: "September 12, 2024 ",
    Status: "mohamedabdelghany937@gmail.com",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Category: "Saudi Arabia ,Riyadh",
    Next_Appointment_Date: "September 12, 2024 ",
    Status: "mohamedabdelghany937@gmail.com",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Category: "Saudi Arabia ,Riyadh",
    Next_Appointment_Date: "September 12, 2024 ",
    Status: "mohamedabdelghany937@gmail.com",
  },
];
