export const data = [
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Number: "12311",
    Court_Name: "Court 1",
    Court_Category: "Family",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Hearing_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Number: "12311",
    Court_Name: "Court 1",
    Court_Category: "Family",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Hearing_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Number: "12311",
    Court_Name: "Court 1",
    Court_Category: "Family",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Hearing_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Number: "12311",
    Court_Name: "Court 1",
    Court_Category: "Family",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Hearing_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Number: "12311",
    Court_Name: "Court 1",
    Court_Category: "Family",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Hearing_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Number: "12311",
    Court_Name: "Court 1",
    Court_Category: "Family",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Hearing_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Number: "12311",
    Court_Name: "Court 1",
    Court_Category: "Family",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Hearing_Dates: "September 12, 2024 12:11 PM",
  },
];
