export const data = [
  {
    id: "TASK-8782",
    Court_Name: "Court1",
    Court_Category: "Criminal",
    Email : "Abc@gmail.com",
    Address: "Saudi Arabia ,Riyadh",
  },
  {
    id: "TASK-8782",
    Court_Name: "Court1",
    Court_Category: "Criminal",
    Email : "xyz@gmail.com",
    Address: "Saudi Arabia ,Riyadh",
  },
  {
    id: "TASK-8782",
    Court_Name: "Court1",
    Court_Category: "Civil",
    Email : "a@gmail.com",
    Address: "Saudi Arabia ,Riyadh",
  },
  {
    id: "TASK-8782",
    Court_Name: "Court6",
    Court_Category: "Family",
    Email : "b@gmail.com",
    Address: "Saudi Arabia ,Riyadh",
  },
  {
    id: "TASK-8782",
    Court_Name: "Court5",
    Court_Category: "Criminal",
    Email : "v@gmail.com",
    Address: "Saudi Arabia ,Riyadh",
  },
  {
    id: "TASK-8782",
    Court_Name: "Court1",
    Court_Category: "Civil",
    Email : "Abc@gmail.com",
    Address: "Saudi Arabia ,Riyadh",
  },
  {
    id: "TASK-8782",
    Court_Name: "Court2",
    Court_Category: "Family",
    Email : "v@gmail.com",
    Address: "Saudi Arabia ,Riyadh",
  },
  {
    id: "TASK-8782",
    Court_Name: "Court3",
    Court_Category: "Civil",
    Email : "Abc@gmail.com",
    Address: "Saudi Arabia ,Riyadh",
  },
];
