export const data = [
  {
    id: "TASK-8782",
    Request_Title: "mohamed",
    Request_Date: "September 12, 2024 12:11 PM",
    Request_Status: "Pending",
    Required_Action: "Agree",
    Associated_Case: "mohamed",
  },
  {
    id: "TASK-8782",
    Request_Title: "mohamed",
    Request_Date: "September 12, 2024 12:11 PM",
    Request_Status: "Pending",
    Required_Action: "Disagree",
    Associated_Case: "mohamed",
  },
  {
    id: "TASK-8782",
    Request_Title: "mohamed",
    Request_Date: "September 12, 2024 12:11 PM",
    Request_Status: "Completed",
    Required_Action: "More",
    Associated_Case: "mohamed",
  },
  {
    id: "TASK-8782",
    Request_Title: "mohamed",
    Request_Date: "September 12, 2024 12:11 PM",
    Request_Status: "Completed",
    Required_Action: "Disagree",
    Associated_Case: "mohamed",
  },
  {
    id: "TASK-8782",
    Request_Title: "mohamed",
    Request_Date: "September 12, 2024 12:11 PM",
    Request_Status: "Responded",
    Required_Action: "Agree",
    Associated_Case: "mohamed",
  },
  {
    id: "TASK-8782",
    Request_Title: "mohamed",
    Request_Date: "September 12, 2024 12:11 PM",
    Request_Status: "Pending",
    Required_Action: "Disagree",
    Associated_Case: "mohamed",
  },
  {
    id: "TASK-8782",
    Request_Title: "mohamed",
    Request_Date: "September 12, 2024 12:11 PM",
    Request_Status: "Responded",
    Required_Action: "More",
    Associated_Case: "mohamed",
  },
];
