export const data = [
  {
    id: "TASK-8782",
    Request_Title: "الطلب رقم 1",
    Request_Date: "September 12, 2024 ",
    Request_Status: "قيدالانتظار",
    Required_Action: "ارسال ملف",
    Associated_Case: "القضية رقم2",
  },
  {
    id: "TASK-8782",
    Request_Title: "الطلب رقم 2",
    Request_Date: "September 17, 2024 ",
    Request_Status: "قيدالانتظار",
    Required_Action: "ارسال المعلومات",
    Associated_Case: "القضية رقم3",
  },
  {
    id: "TASK-8782",
    Request_Title: "الطلب رقم 3",
    Request_Date: "September 21, 2024 ",
    Request_Status: "مكتملة",
    Required_Action: "المزيد",
    Associated_Case: "القضية رقم4",
  },
  {
    id: "TASK-8782",
    Request_Title: "الطلب رقم4",
    Request_Date: "September 17, 2024 ",
    Request_Status: "مكتملة",
    Required_Action: "ارسال المعلومات",
    Associated_Case: "القضية رقم6",
  },
  {
    id: "TASK-8782",
    Request_Title: "الطلب رقم 5",
    Request_Date: "September 10, 2024 ",
    Request_Status: "المزيد",
    Required_Action: "ارسال المعلومات",
    Associated_Case: "القضية رقم5",
  },
  {
    id: "TASK-8782",
    Request_Title: "الطلب رقم6",
    Request_Date: "September 08, 2024 ",
    Request_Status: "قيدالانتظار",
    Required_Action: "ارسال ملف",
    Associated_Case: "القضية رقم6",
  },
  {
    id: "TASK-8782",
    Request_Title: "الطلب رقم7",
    Request_Date: "September 06, 2024 ",
    Request_Status: "تمت الاجابة عليه",
    Required_Action: "المزيد",
    Associated_Case: "القضية رقم 7",
  },
];
