export const data = [
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم 1",
    Case_Name: "القضية رقم1",
    Due_Date: "September 03, 2024 ",
    Remaining_Time: "2 Days",
    Task_Status: "قيد التنفيذ",
    Importance_Level: "ذات اهمية ضعيفة",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم 2",
    Case_Name: "القضية رقم2",
    Due_Date: "September 08, 2024 ",
    Remaining_Time: "2 Days",
    Task_Status: "قيدالانتظار",
    Importance_Level: "متوسطة الاهمية",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم 3",
    Remaining_Time: "2 Days",
    Case_Name: "القضية رقم3",
    Due_Date: "September 10, 2024 ",
    Task_Status: "مكتملة",
    Importance_Level: "متوسطة الاهمية",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم 4",
    Remaining_Time: "1 Days",
    Case_Name: "القضية رقم 4",
    Due_Date: "September 12, 2024 ",
    Task_Status: "قيدالانتظار",
    Importance_Level: "مهمة جدا",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم 5",
    Case_Name: "القضية رقم5",
    Due_Date: "September 11, 2024 ",
    Remaining_Time: "3 Days",
    Task_Status: "مكتملة",
    Importance_Level: "ذات اهمية ضعيفة",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم 6",
    Case_Name: "القضية رقم 6",
    Due_Date: "September 17, 2024 ",
    Remaining_Time: "2 Days",
    Task_Status: "قيدالانتظار",
    Importance_Level: "مهمة جدا",
  },
  {
    id: "TASK-8782",
    Task_Name: "المهمة رقم 6",
    Case_Name: "القضية رقم 7",
    Due_Date: "September 16, 2024 ",
    Remaining_Time: "1 Days",
    Task_Status: "قيد التنفيذ",
    Importance_Level: "متوسطة الاهمية",
  },
];
