export const data = [
  {
    id: "TASK-8782",
    Court_Name: "المحكمة رقم  1",
    Court_Category: "جنائي",
    Email : "Abc@gmail.com",
    Address: "الرياض",
  },
  {
    id: "TASK-8782",
    Court_Name: "المحكمة رقم  2",
    Court_Category: "جنائي",
    Email : "xyz@gmail.com",
    Address: "الدمام",
  },
  {
    id: "TASK-8782",
    Court_Name: "المحكمة رقم  3",
    Court_Category: "مدنى",
    Email : "a@gmail.com",
    Address: "جده",
  },
  {
    id: "TASK-8782",
    Court_Name: "المحكمة رقم  4",
    Court_Category: "عائلى",
    Email : "b@gmail.com",
    Address: "الدمام",
  },
  {
    id: "TASK-8782",
    Court_Name: "Court5",
    Court_Category: "جنائي",
    Email : "v@gmail.com",
    Address: "جده",
  },
  {
    id: "TASK-8782",
    Court_Name: "المحكمة رقم  5",
    Court_Category: "مدنى",
    Email : "Abc@gmail.com",
    Address: "الرياض",
  },
  {
    id: "TASK-8782",
    Court_Name: "المحكمة رقم  6",
    Court_Category: "عائلى",
    Email : "v@gmail.com",
    Address: "جده",
  },
  {
    id: "TASK-8782",
    Court_Name: "المحكمة رقم  7",
    Court_Category: "مدنى",
    Email : "Abc@gmail.com",
    Address: "الرياض",
  },
];
