export const data = [
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Court_Name: "Court 1",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Status: "Progress",
    Client_Name: "mohamed",
    Court_Name: "Court 1",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Court_Name: "Court 1",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Status: "Completed",
    Client_Name: "mohamed",
    Court_Name: "Court 1",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Status: "Progress",
    Client_Name: "mohamed",
    Court_Name: "Court 1",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Status: "Pending",
    Client_Name: "mohamed",
    Court_Name: "Court 1",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 12:11 PM",
  },
  {
    id: "TASK-8782",
    Case_Name: "mohamed",
    Case_Status: "Completed",
    Client_Name: "mohamed",
    Court_Name: "Court 1",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 12:11 PM",
  },
];
