export const data = [
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 1",
    Case_Status: "قيدالانتظار",
    Client_Name: "على",
    Court_Name: "المحكمة رقم 1",
    Case_Number: "12311",
    Key_Dates: "September 19, 2024 ",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 2",
    Case_Status: "قيد التنفيذ",
    Client_Name: "فهد",
    Court_Name: "المحكمة رقم 2",
    Case_Number: "12311",
    Key_Dates: "September 06, 2024 ",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 3",
    Case_Status: "قيدالانتظار",
    Client_Name: "عبدالله",
    Court_Name: "المحكمة رقم 3",
    Case_Number: "12311",
    Key_Dates: "September 26, 2024 ",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 4",
    Case_Status: "مكتملة",
    Client_Name: "احمد",
    Court_Name: "المحكمة رقم 4",
    Case_Number: "12311",
    Key_Dates: "September 29, 2024 ",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 5",
    Case_Status: "قيد التنفيذ",
    Client_Name: "مصطفى",
    Court_Name: "المحكمة رقم 5",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 ",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 6",
    Case_Status: "قيدالانتظار",
    Client_Name: "على",
    Court_Name: "المحكمة رقم 6",
    Case_Number: "12311",
    Key_Dates: "September 12, 2024 ",
  },
  {
    id: "TASK-8782",
    Case_Name: "القضية رقم 7",
    Case_Status: "مكتملة",
    Client_Name: "محمد",
    Court_Name: "المحكمة رقم 7",
    Case_Number: "12311",
    Key_Dates: "September 04, 2024 ",
  },
];
